version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install --legacy-peer-deps
        - export npm_config_loglevel=silent
    build:
      commands:
        - echo "I am running 🏃 on dev" 
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*