name: Detect Changes

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      tf_changed: ${{ steps.check.outputs.tf_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for Terraform changes
        id: check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.tf$'; then
            echo "tf_changed=true" >> $GITHUB_ENV
          else
            echo "tf_changed=false" >> $GITHUB_ENV
          fi

      - name: Show result
        run: echo "Terraform changes detected: ${{ env.tf_changed }}"
