name: Detect Changes

on:
  workflow_call:
    inputs:
      event_name:
        description: 'The name of the event that called the workflow.'
        required: true
        type: string
    outputs:
      folders:
        description: list of folders that have changes
        value: ${{ jobs.detect.outputs.folders }}

jobs:
  detect:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    outputs:
        folders: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get previous commit SHA
        id: base_sha
        run: |
          echo "GIT_BASE=$(git rev-parse HEAD~1)" >> $GITHUB_ENV

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ inputs.event_name == 'release_tags' && env.GIT_BASE || github.event.repository.default_branch }}
          filters: |
            modules:
              - '**/**'
