name: Detect Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: echo "Running detect changes for Kasa"

      - name: Check for changes in IAC directory
        id: changes
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main ${{ github.sha }})
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q '^IAC/'; then
            echo "iac_changed=true" >> $GITHUB_ENV
          else
            echo "iac_changed=false" >> $GITHUB_ENV
          fi

      - name: Load Environment Variables
        run: source $GITHUB_ENV

      - name: Display results
        run: |
          echo "IAC directory changed: ${iac_changed}"
