name: List stages for AWS account

on:
  workflow_call:
    inputs:
      detect_changes:
        description: 'All directories to run commands in'
        required: true
        type: string

    outputs:
      stages:
        description: list of defined stages
        value: ${{ jobs.list-stages.outputs.stages }}

jobs:
  list-stages:
    runs-on: ubuntu-latest
    outputs:
      stages: ${{ steps.stages.outputs.stages }}

    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - name: Retrieve Terraform Backend Configurations
        id: stages
        run: |
          echo "Detect Changes Input: ${{ inputs.detect_changes }}"

          # Convert input string to array
          IFS=', ' read -r -a folders <<< "$(echo "${{ inputs.detect_changes }}" | tr -d '[]')"

          # Initialize the JSON array
          stages=()

          for folder in "${folders[@]}"; do
            if [ -d "$folder/backend" ]; then
              # Find .tfbackend files
              files=$(find "$folder/backend" -type f -name "*.tfbackend" -exec basename {} \;)

              for file in $files; do
                environment="${file%.*}"  # Remove file extension
                stages+=("{\"folder\": \"$folder\", \"environment\": \"$environment\"}")

                # Copy the backend file safely
                mkdir -p "${GITHUB_WORKSPACE}/backend_files/$folder"
                cp "$folder/backend/$file" "${GITHUB_WORKSPACE}/backend_files/$folder/"
              done
            else
              echo "Warning: Directory $folder/backend does not exist. Skipping..."
            fi
          done

          # Convert Bash array to JSON
          stages_json=$(printf '%s\n' "${stages[@]}" | jq -s '.')

          # Output the result
          echo "stages=${stages_json}" >> $GITHUB_OUTPUT
