name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, staging, production]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version  # Verify installation

      - name: Run TFLint
        run: tflint --config .tflint.hcl

      - name: Install Tfsec
        run: |
          curl -sL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec --version  # Verify installation

      - name: Run Tfsec
        run: tfsec .

      - name: Terraform Validate
        run: terraform validate
