name: Generate Terraform Docs

on:
  - pull_request

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render Terraform Docs and Push Changes Back to PR
        uses: terraform-docs/gh-actions@v1
        with:
          find-dir: modules/
          output-file: README.md
          output-method: inject
          git-push: "true"
