name: Terraform Apply

on:
  workflow_call:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: '${{ vars.TF_USER_AWS_KEY }}'
            aws-secret-access-key: '${{ vars.TF_USER_AWS_SECRET }}'
            aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  

      - name: Terraform Init
        run: |
          terraform init -backend-config modules/backend/dev.tfbackend

      - name: Terraform Apply
        if: github.event_name == 'push'  # Only applies during a push to the main branch
        run: |
          terraform apply --var-file tfvars/dev.tfvars -auto-approve

      - name: Output Apply Results
        run: |
          echo "Terraform apply completed successfully."
