name: Terraform Validation

on:
  workflow_call:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: '${{ vars.TF_USER_AWS_KEY }}'
            aws-secret-access-key: '${{ vars.TF_USER_AWS_SECRET }}'
            aws-region: us-east-1 

      - name: Terraform Init
        run: |
          terraform init -backend-config modules/backend/dev.tfbackend

      - name: Terraform Validate
        id: terraform-validate
        run: |
          terraform validate
          terraform fmt -check -diff

      - name: Output Validation Results
        run: |
          echo "Terraform validation completed successfully."
