name: Trigger Terraform pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:

  detect-changes:
    uses: ./.github/workflows/detect_changes.yml
    with:
      event_name: pull_request
    permissions:
      id-token: write
      contents: read
      pull-requests: read

  list-stages:
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.folders != '[]'}}
    uses: ./.github/workflows/terraform_stages.yml
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    with:
      detect_changes: ${{needs.detect-changes.outputs.folders}}

  validate:
    needs: [list-stages]
    if: |
      ${{ needs.detect-changes.outputs.folders != '[]'}}
    uses: ./.github/workflows/terraform_validate.yml
    permissions:
      id-token: write
      contents: read
      pull-requests: write 
  plan:
    needs: [list-stages, validate]
    if: |
      ${{ needs.detect-changes.outputs.folders != '[]'}}
    uses: ./.github/workflows/terraform_plan.yml
    permissions:
      id-token: write
      contents: read
      pull-requests: write

  apply:
    needs: [plan]
    if: |
      ${{ needs.detect-changes.outputs.folders != '[]'}}
    uses: ./.github/workflows/terraform_apply.yml
    permissions:
      id-token: write
      contents: read
      pull-requests: write